<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Chris82111.LibCsharpStaticGitCollection.TestNuget</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Chris82111.LibCsharpStaticGitCollection" Version="1.0.0" />
    <PackageReference Include="MSTest" Version="4.4.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
